name: Upload Asset

on:
  release:
    types: [created]

env:
  python-version: "3.9"
  asset-name: BoxLogImporter.zip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t ./.python_packages; fi

    - name: Create Zip file
      run: |
        zip -r ${{ env.asset-name }} host.json requirements.txt BoxLogImporter .python_packages

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url}}
        asset_path: ${{ env.asset-name }}
        asset_name: ${{ env.asset-name }}
        asset_content_type: application/zip
